### ISSUE TITLE
Undefined method `[]' for nul:NilClass using mysql_client and WordPress cookbook

### ISSUE THREAD

**Issue by bmurtagh** [chef-cookbooks/database#179]
Hello, 

I'm attempting to install the [Wordpress v3.0.0](https://github.com/brint/wordpress-cookbook) cookbook on an EC2 instance, but during the Chef run (after successful _berks init_, _berks vendor_, etc.) I get the error message below and I cannot figure out why for the life of me.

Searching through the open issues here, I do not see the same problem reported. Any guidance or advice is appreciated.

```
2015-09-27 16:17:09,629 P2294 [INFO] 	[2015-09-27T16:17:06+00:00] INFO: Processing mysql_client[default] action create (wordpress::database line 24)
2015-09-27 16:17:09,629 P2294 [INFO]
2015-09-27 16:17:09,629 P2294 [INFO] 	================================================================================
2015-09-27 16:17:09,629 P2294 [INFO] 	Error executing action `create` on resource 'mysql_client[default]'
2015-09-27 16:17:09,630 P2294 [INFO] 	================================================================================
2015-09-27 16:17:09,630 P2294 [INFO]
2015-09-27 16:17:09,630 P2294 [INFO] 	NoMethodError
2015-09-27 16:17:09,630 P2294 [INFO] 	-------------
2015-09-27 16:17:09,630 P2294 [INFO] 	undefined method `[]' for nil:NilClass
2015-09-27 16:17:09,630 P2294 [INFO]
2015-09-27 16:17:09,630 P2294 [INFO] 	Cookbook Trace:
2015-09-27 16:17:09,630 P2294 [INFO] 	---------------
2015-09-27 16:17:09,630 P2294 [INFO] 	/var/chef/chef-repo/.chef/local-mode-cache/cache/cookbooks/mysql/libraries/helpers.rb:372:in `package_name_for'
2015-09-27 16:17:09,631 P2294 [INFO] 	/var/chef/chef-repo/.chef/local-mode-cache/cache/cookbooks/mysql/libraries/helpers.rb:403:in `client_package'
2015-09-27 16:17:09,631 P2294 [INFO] 	/var/chef/chef-repo/.chef/local-mode-cache/cache/cookbooks/mysql/libraries/helpers.rb:29:in `client_package_name'
2015-09-27 16:17:09,631 P2294 [INFO] 	/var/chef/chef-repo/.chef/local-mode-cache/cache/cookbooks/mysql/libraries/provider_mysql_client.rb:20:in `block in <class:MysqlClient>'
2015-09-27 16:17:09,631 P2294 [INFO]
2015-09-27 16:17:09,631 P2294 [INFO] 	Resource Declaration:
2015-09-27 16:17:09,631 P2294 [INFO] 	---------------------
2015-09-27 16:17:09,631 P2294 [INFO] 	# In /var/chef/chef-repo/.chef/local-mode-cache/cache/cookbooks/wordpress/recipes/database.rb
2015-09-27 16:17:09,631 P2294 [INFO]
2015-09-27 16:17:09,632 P2294 [INFO] 	 24:   mysql_client 'default' do
2015-09-27 16:17:09,632 P2294 [INFO] 	 25:     action :create
2015-09-27 16:17:09,632 P2294 [INFO] 	 26:   end
2015-09-27 16:17:09,632 P2294 [INFO] 	 27: end
2015-09-27 16:17:09,632 P2294 [INFO]
2015-09-27 16:17:09,632 P2294 [INFO] 	Compiled Resource:
2015-09-27 16:17:09,632 P2294 [INFO] 	------------------
2015-09-27 16:17:09,632 P2294 [INFO] 	# Declared in /var/chef/chef-repo/.chef/local-mode-cache/cache/cookbooks/wordpress/recipes/database.rb:24:in `from_file'
2015-09-27 16:17:09,633 P2294 [INFO]
2015-09-27 16:17:09,633 P2294 [INFO] 	mysql_client("default") do
2015-09-27 16:17:09,633 P2294 [INFO] 	  action [:create]
2015-09-27 16:17:09,633 P2294 [INFO] 	  retries 0
2015-09-27 16:17:09,633 P2294 [INFO] 	  retry_delay 2
2015-09-27 16:17:09,633 P2294 [INFO] 	  default_guard_interpreter :default
2015-09-27 16:17:09,633 P2294 [INFO] 	  declared_type :mysql_client
2015-09-27 16:17:09,633 P2294 [INFO] 	  cookbook_name "wordpress"
2015-09-27 16:17:09,634 P2294 [INFO] 	  recipe_name "database"
2015-09-27 16:17:09,634 P2294 [INFO] 	end
2015-09-27 16:17:09,634 P2294 [INFO]
2015-09-27 16:17:09,634 P2294 [INFO] 	[2015-09-27T16:17:06+00:00] INFO: Running queued delayed notifications before re-raising exception
2015-09-27 16:17:09,634 P2294 [INFO] 	[2015-09-27T16:17:06+00:00] INFO: template[/etc/httpd/mods-available/deflate.conf] sending reload action to service[apache2] (delayed)
2015-09-27 16:17:09,634 P2294 [INFO] 	[2015-09-27T16:17:06+00:00] INFO: Processing service[apache2] action reload (apache2::default line 206)
2015-09-27 16:17:09,634 P2294 [INFO] 	[2015-09-27T16:17:06+00:00] INFO: service[apache2] reloaded
2015-09-27 16:17:09,634 P2294 [INFO] 	[2015-09-27T16:17:06+00:00] INFO: template[/etc/sysconfig/httpd] sending restart action to service[apache2] (delayed)
2015-09-27 16:17:09,634 P2294 [INFO] 	[2015-09-27T16:17:06+00:00] INFO: Processing service[apache2] action restart (apache2::default line 206)
2015-09-27 16:17:09,635 P2294 [INFO] 	[2015-09-27T16:17:07+00:00] INFO: service[apache2] restarted
2015-09-27 16:17:09,635 P2294 [INFO] 	[2015-09-27T16:17:07+00:00] ERROR: Running exception handlers
2015-09-27 16:17:09,635 P2294 [INFO] 	[2015-09-27T16:17:07+00:00] ERROR: Exception handlers complete
2015-09-27 16:17:09,635 P2294 [INFO] 	[2015-09-27T16:17:07+00:00] FATAL: Stacktrace dumped to /var/chef/chef-repo/.chef/local-mode-cache/cache/chef-stacktrace.out
2015-09-27 16:17:09,635 P2294 [INFO] 	[2015-09-27T16:17:07+00:00] ERROR: mysql_client[default] (wordpress::database line 24) had an error: NoMethodError: undefined method `[]' for nil:NilClass
2015-09-27 16:17:09,635 P2294 [INFO] 	[2015-09-27T16:17:09+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
2015-09-27 16:17:09,635 P2294 [INFO] ------------------------------------------------------------
2015-09-27 16:17:09,636 P2294 [ERROR] Exited with error code 1
```

**Comment by eric-tucker** [comment]
See #381 and #382.  This is related to Amazon Linux 2015.09.

Someone needs to merge one of the two above PRs.  The cookbook does not function on Amazon Linux which is a huge market.

**Comment by iennae** [comment]
@bmurtagh,

As of October 5, 2015 a fix was pulled into the mysql cookbook. Are you still seeing this problem? Thanks!

**Comment by iennae** [comment]
@bmurtagh If you're still having a problem, please reopen.
